export const appreticeConstants = {
    GETAPPRETICEINFO_REQUEST: "GETAPPRETICEINFO_REQUEST",
    GETAPPRETICEINFO_SUCCESS: "GETAPPRETICEINFO_SUCCESS",
    GETAPPRETICEINFO_FAILURE: "GETAPPRETICEINFO_FAILURE",

    UPDATEAPPRETICEINFO_REQUEST: "UPDATEAPPRETICEINFO_REQUEST",
    UPDATEAPPRETICEINFO_SUCCESS: "UPDATEAPPRETICEINFO_SUCCESS",
    UPDATEAPPRETICEINFO_FAILURE: "UPDATEAPPRETICEINFO_FAILURE",
    UPDATEAPPRETICEINFO_FINISH: "UPDATEAPPRETICEINFO_FINISH",
}