export const rolConstant = {
    GETROLES_REQUEST: "GETROLES_REQUEST",
    GETROLES_SUCCESS: "GETROLES_SUCCESS",
    GETROLES_FAILURE: "GETROLES_FAILURE",

    ADDROLES_REQUEST: "ADDROLES_REQUEST",
    ADDROLES_SUCCESS: "ADDROLES_SUCCESS",
    ADDROLES_FAILURE: "ADDROLES_FAILURE",

    GETROLINFO_REQUEST: "GETROLINFO_REQUEST",
    GETROLINFO_SUCCESS: "GETROLINFO_SUCCESS",
    GETROLINFO_FAILURE: "GETROLINFO_FAILURE",

    GETROLCAPACITIES_REQUEST: "GETROLCAPACITIES_REQUEST",
    GETROLCAPACITIES_SUCCESS: "GETROLCAPACITIES_SUCCESS",
    GETROLCAPACITIES_FAILURE: "GETROLCAPACITIES_FAILURE",
};
