export const searchConstants = {
    SEARCHAPPRETICE_REQUEST: "SEARCHAPPRETICE_REQUEST",
    SEARCHAPPRETICE_SUCCESS: "SEARCHAPPRETICE_SUCCESS",
    SEARCHAPPRETICE_FAILURE: "SEARCHAPPRETICE_FAILURE",

    SEARCHONEAPRETICE_REQUEST: "SEARCHONEAPRETICE_REQUEST",
    SEARCHONEAPRETICE_SUCCESS: "SEARCHONEAPRETICE_SUCCESS",
    SEARCHONEAPRETICE_FAILURE: "SEARCHONEAPRETICE_FAILURE",
    FINISHSEARCHED: "FINISHSEARCHED",

    HIDESEARCHEDMODAL: "HIDESEARCHEDMODAL",
};
