export const uploadConstants = {
    APPRENTICESUPLOAD_REQUEST: "APPRENTICESUPLOAD_REQUEST",
    APPRENTICESUPLOAD_SUCCESS: "APPRENTICESUPLOAD_SUCCESS",
    APPRENTICESUPLOAD_FAILURE: "APPRENTICESUPLOAD_FAILURE",

    UPLOADALERT_HIDE: "UPLOADALERT_HIDE",
};
