export const uploadConstants = {
    APPRENTICESUPLOAD_REQUEST: "APPRENTICESUPLOAD_REQUEST",
    APPRENTICESUPLOAD_SUCCESS: "APPRENTICESUPLOAD_SUCCESS",
    APPRENTICESUPLOAD_FAILURE: "APPRENTICESUPLOAD_FAILURE",

    UPLOADNEWFILESOLICITY_REQUEST: "UPLOADNEWFILESOLICITY_REQUEST",
    UPLOADNEWFILESOLICITY_SUCCESS: "UPLOADNEWFILESOLICITY_SUCCESS",
    UPLOADNEWFILESOLICITY_FAILURE: "UPLOADNEWFILESOLICITY_FAILURE",
    UPLOADNEWFILESOLICITY_CLEAR: "UPLOADNEWFILESOLICITY_CLEAR",

    UPLOADALERT_HIDE: "UPLOADALERT_HIDE",
};
